### ISSUE TITLE
Debian/Emacs: LSP error on basic C inlucdes

### ISSUE THREAD

**Issue by ntn888** [clangd/clangd#1362]
Please describe the problem.
LSP error on basic C inlucdes:

![Screenshot from 2022-11-04 19-18-53](https://user-images.githubusercontent.com/41226903/199926127-0f1caff0-2c5a-47d4-84b8-df53b53aadcc.png)

**Logs**

*clangd::stderr*
Logs clangd::stderr [clangd log](https://pastecode.io/s/8n1v3dpf)

*lsp-log*:
```
Command "ccls" is not present on the path.
Command "clangd --header-insertion-decorators=0" is present on the path.
Command "ccls" is not present on the path.
Command "clangd --header-insertion-decorators=0" is present on the path.
Found the following clients for /home/ajit/work/pico/my/myblink2/src/myblink.c: (server-id clangd, priority -1)
The following clients were selected based on priority: (server-id clangd, priority -1)
Command "ccls" is not present on the path.
Command "clangd --header-insertion-decorators=0" is present on the path.
Command "ccls" is not present on the path.
Command "clangd --header-insertion-decorators=0" is present on the path.
Found the following clients for /home/ajit/work/pico/my/myblink2/pico/stdlib.h: (server-id clangd, priority -1)
The following clients were selected based on priority: (server-id clangd, priority -1)
Command "ccls" is not present on the path.
Command "clangd --header-insertion-decorators=0" is present on the path.
Command "ccls" is not present on the path.
Command "clangd --header-insertion-decorators=0" is present on the path.
Found the following clients for /home/ajit/work/pico/pico-sdk/src/common/pico_stdlib/include/pico/stdlib.h: (server-id clangd, priority -1)
The following clients were selected based on priority: (server-id clangd, priority -1)
Cancelling textDocument/documentLink(58) in hook post-command-hook
Cancelling textDocument/codeAction(57) in hook post-command-hook
```

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**

Output of `clangd --version`: Debian clangd version 11.0.1-2

Editor/LSP plugin: Emacs/LSP

Operating system: Debian 11

Edit: found out that by not generating the compile_commands.json file the stdio.h error goes away?!

**Comment by ntn888** [comment]
Edit2: I found this: [stdio.h and FPU errors in Neovim using clangd LSP](https://stackoverflow.com/questions/72501038/stdio-h-and-fpu-errors-in-neovim-using-clangd-lsp)

so in config.yaml i added:
```
CompileFlags:
    Add: ['--sysroot=/usr/lib/gcc/arm-none-eabi/8.3.1/']
```
and the issue persists...

**Comment by HighCommander4** [comment]
Are you cross-compiling for ARM? If so, then using `--query-driver` as discussed at https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc should fix the issue.

If you're not able to get it to work, please share [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs).

**Comment by ntn888** [comment]
thanks for your response, I wasn't able to figure out where to plug in the query-driver command. maybe i'll confirm this at the doom/emacs forums?

**Comment by HighCommander4** [comment]
> thanks for your response, I wasn't able to figure out where to plug in the query-driver command. maybe i'll confirm this at the doom/emacs forums?

It's a command-line argument to clangd. I'm not sure where it's specified in emacs, but from your log I can see you're already passing `--header-insertion-decorators=0`, so it would be in the same place.

**Comment by ntn888** [comment]
yeah, i did try it beside. but i 'm not familiar with the syntax. thanks for the tip, i'll double check

**Comment by ntn888** [comment]
hi thanks again, i did some digging and was able to pass the new argument
issue still persists

verbose log:
```
I[07:43:24.125] clangd version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
I[07:43:24.125] Features: linux+grpc
I[07:43:24.125] PID: 31523
I[07:43:24.125] Working directory: /home/ajit/work/pico/my/myblink3
I[07:43:24.125] argv[0]: /home/ajit/.emacs.d/.local/etclsp/clangd/clangd_13.0.0/bin/clangd
I[07:43:24.125] argv[1]: --query-driver=/usr/lib/gcc/arm-none-eabi/8.3.1/
I[07:43:24.125] argv[2]: --header-insertion-decorators=0
I[07:43:24.125] argv[3]: --log=verbose
V[07:43:24.125] User config file is /home/ajit/.config/clangd/config.yaml
I[07:43:24.125] Starting LSP over stdin/stdout
V[07:43:24.125] <<< {"id":1,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"callHierarchy":{"dynamicRegistration":false},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"dynamicRegistration":true,"isPreferredSupport":true,"resolveSupport":{"properties":["edit","command"]}},"completion":{"completionItem":{"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"insertReplaceSupport":true,"insertTextModeSupport":{"valueSet":[1,2]},"resolveAdditionalTextEditsSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits","command"]},"snippetSupport":true},"contextSupport":true,"dynamicRegistration":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"documentSymbol":{"hierarchicalDocumentSymbolSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"formatting":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"linkedEditingRange":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"publishDiagnostics":{"relatedInformation":true,"tagSupport":{"valueSet":[1,2]},"versionSupport":true},"rangeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"selectionRange":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"typeHierarchy":{"dynamicRegistration":true}},"window":{"showDocument":{"support":true},"workDoneProgress":true},"workspace":{"applyEdit":true,"codeLens":{"refreshSupport":true},"configuration":true,"didChangeWatchedFiles":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":false},"fileOperations":{"didCreate":false,"didDelete":false,"didRename":true,"willCreate":false,"willDelete":false,"willRename":true},"symbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"emacs","version":"GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)\n of 2021-03-28, modified by Debian"},"initializationOptions":null,"processId":null,"rootPath":"/home/ajit/work/pico/my/myblink3","rootUri":"file:///home/ajit/work/pico/my/myblink3","workDoneToken":"1"}}

I[07:43:24.125] <-- initialize(1)
I[07:43:24.125] --> reply:initialize(1) 0 ms
V[07:43:24.126] >>> {"id":1,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"allCommitCharacters":[" ","\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\"","'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"implementationProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":["declaration","deprecated","deduced","readonly","static","abstract","dependentName","defaultLibrary","functionScope","classScope","fileScope","globalScope"],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","interface","enum","enumMember","type","type","unknown","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d) linux+grpc x86_64-unknown-linux-gnu"}}}

V[07:43:24.228] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}

I[07:43:24.228] <-- initialized
V[07:43:24.229] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"c","text":"//#include \"myblink.h\"\n//\n#include <stdio.h>\n\n#include \"pico/stdlib.h\"\n//#include \"pico/stdlib.h\"\n\nint main(void)\n{\n\n\n    return 0;\n}\n","uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c","version":0}}}

I[07:43:24.229] <-- textDocument/didOpen
V[07:43:24.230] config note at /home/ajit/.config/clangd/config.yaml:1:0: Parsing config fragment
V[07:43:24.230] config note at /home/ajit/.config/clangd/config.yaml:1:0: Parsed 1 fragments from file
V[07:43:24.230] Config fragment: compiling /home/ajit/.config/clangd/config.yaml:1 -> 0x00007FEFB4002C90 (trusted=true)
I[07:43:24.230] --> textDocument/publishDiagnostics
V[07:43:24.231] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///home/ajit/.config/clangd/config.yaml"}}

I[07:43:24.231] Loaded compilation database from /home/ajit/work/pico/my/myblink3/compile_commands.json
V[07:43:24.231] Broadcasting compilation database from /home/ajit/work/pico/my/myblink3
V[07:43:24.231] System include extraction: not allowed driver /usr/bin/arm-none-eabi-gcc
I[07:43:24.231] ASTWorker building file /home/ajit/work/pico/my/myblink3/src/myblink.c version 0 with command 
[/home/ajit/work/pico/my/myblink3]
/usr/bin/arm-none-eabi-gcc --target=arm-none-eabi -DLIB_PICO_BIT_OPS=1 -DLIB_PICO_BIT_OPS_PICO=1 -DLIB_PICO_DIVIDER=1 -DLIB_PICO_DIVIDER_HARDWARE=1 -DLIB_PICO_DOUBLE=1 -DLIB_PICO_DOUBLE_PICO=1 -DLIB_PICO_FLOAT=1 -DLIB_PICO_FLOAT_PICO=1 -DLIB_PICO_INT64_OPS=1 -DLIB_PICO_INT64_OPS_PICO=1 -DLIB_PICO_MALLOC=1 -DLIB_PICO_MEM_OPS=1 -DLIB_PICO_MEM_OPS_PICO=1 -DLIB_PICO_PLATFORM=1 -DLIB_PICO_PRINTF=1 -DLIB_PICO_PRINTF_PICO=1 -DLIB_PICO_RUNTIME=1 -DLIB_PICO_STANDARD_LINK=1 -DLIB_PICO_STDIO=1 -DLIB_PICO_STDIO_UART=1 -DLIB_PICO_STDLIB=1 -DLIB_PICO_SYNC=1 -DLIB_PICO_SYNC_CORE=1 -DLIB_PICO_SYNC_CRITICAL_SECTION=1 -DLIB_PICO_SYNC_MUTEX=1 -DLIB_PICO_SYNC_SEM=1 -DLIB_PICO_TIME=1 -DLIB_PICO_UTIL=1 "-DPICO_BOARD=\"pico\"" -DPICO_BUILD=1 "-DPICO_CMAKE_BUILD_TYPE=\"Release\"" -DPICO_COPY_TO_RAM=0 -DPICO_CXX_ENABLE_EXCEPTIONS=0 -DPICO_NO_FLASH=0 -DPICO_NO_HARDWARE=0 -DPICO_ON_DEVICE=1 "-DPICO_TARGET_NAME=\"myblink\"" -DPICO_USE_BLOCKED_RAM=0 -I/home/ajit/work/pico/pico-sdk/src/common/pico_stdlib/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_gpio/include -I/home/ajit/work/pico/pico-sdk/src/common/pico_base/include -I/home/ajit/work/pico/my/myblink3/generated/pico_base -I/home/ajit/work/pico/pico-sdk/src/boards/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/pico_platform/include -I/home/ajit/work/pico/pico-sdk/src/rp2040/hardware_regs/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_base/include -I/home/ajit/work/pico/pico-sdk/src/rp2040/hardware_structs/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_claim/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_sync/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_irq/include -I/home/ajit/work/pico/pico-sdk/src/common/pico_sync/include -I/home/ajit/work/pico/pico-sdk/src/common/pico_time/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_timer/include -I/home/ajit/work/pico/pico-sdk/src/common/pico_util/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_uart/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_divider/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/pico_runtime/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_clocks/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_resets/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_pll/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_vreg/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_watchdog/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_xosc/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/pico_printf/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/pico_bootrom/include -I/home/ajit/work/pico/pico-sdk/src/common/pico_bit_ops/include -I/home/ajit/work/pico/pico-sdk/src/common/pico_divider/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/pico_double/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/pico_int64_ops/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/pico_float/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/pico_malloc/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/boot_stage2/include -I/home/ajit/work/pico/pico-sdk/src/common/pico_binary_info/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/pico_stdio/include -I/home/ajit/work/pico/pico-sdk/src/rp2_common/pico_stdio_uart/include -mcpu=cortex-m0plus -mthumb -O3 -DNDEBUG -ffunction-sections -fdata-sections -std=gnu11 -o CMakeFiles/myblink.dir/src/myblink.c.obj -c --sysroot=/usr/lib/gcc/arm-none-eabi/8.3.1/ -resource-dir=/home/ajit/.emacs.d/.local/etclsp/clangd/clangd_13.0.0/lib/clang/13.0.0 -- /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:24.232] --> window/workDoneProgress/create(0)
V[07:43:24.232] >>> {"id":0,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"backgroundIndexProgress"}}

I[07:43:24.232] Enqueueing 1 commands for indexing
V[07:43:24.232] Driver produced command: cc1 -cc1 -triple thumbv6m-none-unknown-eabi -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name myblink.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -fno-verbose-asm -mconstructor-aliases -nostdsysteminc -target-cpu cortex-m0plus -target-feature +soft-float-abi -target-feature -crc -target-feature -dsp -target-feature -mve -target-feature -ras -target-feature -sb -target-feature -i8mm -target-feature -lob -target-feature -cdecp0 -target-feature -cdecp1 -target-feature -cdecp2 -target-feature -cdecp3 -target-feature -cdecp4 -target-feature -cdecp5 -target-feature -cdecp6 -target-feature -cdecp7 -target-feature -hwdiv-arm -target-feature -hwdiv -target-feature -vfp2 -target-feature -vfp2sp -target-feature -vfp3 -target-feature -vfp3d16 -target-feature -vfp3d16sp -target-feature -vfp3sp -target-feature -fp16 -target-feature -vfp4 -target-feature -vfp4d16 -target-feature -vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature -fp-armv8d16 -target-feature -fp-armv8d16sp -target-feature -fp-armv8sp -target-feature -fullfp16 -target-feature -fp64 -target-feature -d32 -target-feature -neon -target-feature -dotprod -target-feature -fp16fml -target-feature -bf16 -target-feature -mve.fp -target-feature -fpregs -target-feature -crypto -target-feature -sha2 -target-feature -aes -target-feature +strict-align -target-abi aapcs -mfloat-abi soft -fallow-half-arguments-and-returns -debugger-tuning=gdb -ffunction-sections -fdata-sections -fcoverage-compilation-dir=/home/ajit/work/pico/my/myblink3 -resource-dir /home/ajit/.emacs.d/.local/etclsp/clangd/clangd_13.0.0/lib/clang/13.0.0 -D LIB_PICO_BIT_OPS=1 -D LIB_PICO_BIT_OPS_PICO=1 -D LIB_PICO_DIVIDER=1 -D LIB_PICO_DIVIDER_HARDWARE=1 -D LIB_PICO_DOUBLE=1 -D LIB_PICO_DOUBLE_PICO=1 -D LIB_PICO_FLOAT=1 -D LIB_PICO_FLOAT_PICO=1 -D LIB_PICO_INT64_OPS=1 -D LIB_PICO_INT64_OPS_PICO=1 -D LIB_PICO_MALLOC=1 -D LIB_PICO_MEM_OPS=1 -D LIB_PICO_MEM_OPS_PICO=1 -D LIB_PICO_PLATFORM=1 -D LIB_PICO_PRINTF=1 -D LIB_PICO_PRINTF_PICO=1 -D LIB_PICO_RUNTIME=1 -D LIB_PICO_STANDARD_LINK=1 -D LIB_PICO_STDIO=1 -D LIB_PICO_STDIO_UART=1 -D LIB_PICO_STDLIB=1 -D LIB_PICO_SYNC=1 -D LIB_PICO_SYNC_CORE=1 -D LIB_PICO_SYNC_CRITICAL_SECTION=1 -D LIB_PICO_SYNC_MUTEX=1 -D LIB_PICO_SYNC_SEM=1 -D LIB_PICO_TIME=1 -D LIB_PICO_UTIL=1 -D "PICO_BOARD=\"pico\"" -D PICO_BUILD=1 -D "PICO_CMAKE_BUILD_TYPE=\"Release\"" -D PICO_COPY_TO_RAM=0 -D PICO_CXX_ENABLE_EXCEPTIONS=0 -D PICO_NO_FLASH=0 -D PICO_NO_HARDWARE=0 -D PICO_ON_DEVICE=1 -D "PICO_TARGET_NAME=\"myblink\"" -D PICO_USE_BLOCKED_RAM=0 -I /home/ajit/work/pico/pico-sdk/src/common/pico_stdlib/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_gpio/include -I /home/ajit/work/pico/pico-sdk/src/common/pico_base/include -I /home/ajit/work/pico/my/myblink3/generated/pico_base -I /home/ajit/work/pico/pico-sdk/src/boards/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/pico_platform/include -I /home/ajit/work/pico/pico-sdk/src/rp2040/hardware_regs/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_base/include -I /home/ajit/work/pico/pico-sdk/src/rp2040/hardware_structs/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_claim/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_sync/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_irq/include -I /home/ajit/work/pico/pico-sdk/src/common/pico_sync/include -I /home/ajit/work/pico/pico-sdk/src/common/pico_time/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_timer/include -I /home/ajit/work/pico/pico-sdk/src/common/pico_util/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_uart/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_divider/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/pico_runtime/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_clocks/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_resets/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_pll/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_vreg/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_watchdog/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/hardware_xosc/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/pico_printf/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/pico_bootrom/include -I /home/ajit/work/pico/pico-sdk/src/common/pico_bit_ops/include -I /home/ajit/work/pico/pico-sdk/src/common/pico_divider/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/pico_double/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/pico_int64_ops/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/pico_float/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/pico_malloc/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/boot_stage2/include -I /home/ajit/work/pico/pico-sdk/src/common/pico_binary_info/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/pico_stdio/include -I /home/ajit/work/pico/pico-sdk/src/rp2_common/pico_stdio_uart/include -D NDEBUG -isysroot /usr/lib/gcc/arm-none-eabi/8.3.1/ -internal-isystem /home/ajit/.emacs.d/.local/etclsp/clangd/clangd_13.0.0/lib/clang/13.0.0/include -internal-isystem /usr/lib/gcc/arm-none-eabi/8.3.1/include -O3 -std=gnu11 -fdebug-compilation-dir=/home/ajit/work/pico/my/myblink3 -ferror-limit 19 -fno-signed-char -fgnuc-version=4.2.1 -vectorize-loops -vectorize-slp -faddrsig -x c /home/ajit/work/pico/my/myblink3/src/myblink.c
V[07:43:24.232] Building first preamble for /home/ajit/work/pico/my/myblink3/src/myblink.c version 0
V[07:43:24.234] Failed to load shard: /home/ajit/work/pico/my/myblink3/build/generated/pico_base/pico/version.h
V[07:43:24.235] Failed to load shard: /home/ajit/work/pico/my/myblink3/build/generated/pico_base/pico/config_autogen.h
V[07:43:24.240] BackgroundIndex: building version 1 after loading index from disk
V[07:43:24.250] BackgroundIndex: serving version 1 (3311908 bytes)
E[07:43:24.250] Background-index: Couldn't read /home/ajit/work/pico/my/myblink3/build/generated/pico_base/pico/config_autogen.h to validate stored index: No such file or directory
E[07:43:24.251] Background-index: Couldn't read /home/ajit/work/pico/my/myblink3/build/generated/pico_base/pico/version.h to validate stored index: No such file or directory
V[07:43:24.279] <<< {"id":2,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":10,"line":2},"start":{"character":10,"line":2}},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.279] <-- textDocument/codeAction(2)
V[07:43:24.279] <<< {"id":3,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.279] <-- textDocument/documentLink(3)
V[07:43:24.279] <<< {"id":4,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":10,"line":2},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.279] <-- textDocument/documentHighlight(4)
V[07:43:24.279] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":2}}

I[07:43:24.279] <-- $/cancelRequest
V[07:43:24.279] <<< {"id":5,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":10,"line":2},"start":{"character":10,"line":2}},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.279] <-- textDocument/codeAction(5)
V[07:43:24.279] <<< {"id":6,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.279] <-- textDocument/documentLink(6)
V[07:43:24.279] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":4}}

I[07:43:24.279] <-- $/cancelRequest
V[07:43:24.279] <<< {"id":7,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":10,"line":2},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.279] <-- textDocument/documentHighlight(7)
V[07:43:24.294] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":5}}

I[07:43:24.294] <-- $/cancelRequest
V[07:43:24.294] <<< {"id":8,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":10,"line":2},"start":{"character":10,"line":2}},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.294] <-- textDocument/codeAction(8)
V[07:43:24.294] <<< {"id":9,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.294] <-- textDocument/documentLink(9)
V[07:43:24.294] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":7}}

I[07:43:24.294] <-- $/cancelRequest
V[07:43:24.294] <<< {"id":10,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":10,"line":2},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.294] <-- textDocument/documentHighlight(10)
V[07:43:24.294] <<< {"id":0,"jsonrpc":"2.0","result":null}

I[07:43:24.294] <-- reply(0)
I[07:43:24.294] --> $/progress
V[07:43:24.294] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"begin","percentage":0,"title":"indexing"}}}

I[07:43:24.294] --> $/progress
V[07:43:24.294] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"end"}}}

V[07:43:24.359] indexed preamble AST for /home/ajit/work/pico/my/myblink3/src/myblink.c version 0:
  symbol slab: 13187 symbols, 3649328 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 0 relations, 24 bytes
V[07:43:24.462] Build dynamic index for header symbols with estimated memory usage of 7961436 bytes
V[07:43:24.464] Built preamble of size 1987280 for file /home/ajit/work/pico/my/myblink3/src/myblink.c version 0
V[07:43:24.470] indexed file AST for /home/ajit/work/pico/my/myblink3/src/myblink.c version 0:
  symbol slab: 1 symbols, 4448 bytes
  ref slab: 1 symbols, 1 refs, 4248 bytes
  relations slab: 0 relations, 24 bytes
V[07:43:24.470] Build dynamic index for main-file symbols with estimated memory usage of 11520 bytes
I[07:43:24.470] --> textDocument/publishDiagnostics
V[07:43:24.470] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"pp_file_not_found","message":"'stdio.h' file not found","range":{"end":{"character":18,"line":2},"start":{"character":9,"line":2}},"relatedInformation":[],"severity":1,"source":"clang"}],"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c","version":0}}

I[07:43:24.470] --> reply:textDocument/codeAction(2) 191 ms, error: Task was cancelled.
V[07:43:24.470] >>> {"error":{"code":-32800,"message":"Request cancelled"},"id":2,"jsonrpc":"2.0"}

V[07:43:24.470] ASTWorker running DocumentLinks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:24.470] --> reply:textDocument/documentLink(3) 191 ms
V[07:43:24.470] >>> {"id":3,"jsonrpc":"2.0","result":[{"range":{"end":{"character":24,"line":4},"start":{"character":9,"line":4}},"target":"file:///home/ajit/work/pico/pico-sdk/src/common/pico_stdlib/include/pico/stdlib.h"}]}

I[07:43:24.470] --> reply:textDocument/documentHighlight(4) 191 ms, error: Task was cancelled.
V[07:43:24.470] >>> {"error":{"code":-32800,"message":"Request cancelled"},"id":4,"jsonrpc":"2.0"}

I[07:43:24.470] --> reply:textDocument/codeAction(5) 191 ms, error: Task was cancelled.
V[07:43:24.470] >>> {"error":{"code":-32800,"message":"Request cancelled"},"id":5,"jsonrpc":"2.0"}

V[07:43:24.470] ASTWorker running DocumentLinks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:24.470] --> reply:textDocument/documentLink(6) 191 ms
V[07:43:24.470] >>> {"id":6,"jsonrpc":"2.0","result":[{"range":{"end":{"character":24,"line":4},"start":{"character":9,"line":4}},"target":"file:///home/ajit/work/pico/pico-sdk/src/common/pico_stdlib/include/pico/stdlib.h"}]}

I[07:43:24.470] --> reply:textDocument/documentHighlight(7) 191 ms, error: Task was cancelled.
V[07:43:24.470] >>> {"error":{"code":-32800,"message":"Request cancelled"},"id":7,"jsonrpc":"2.0"}

V[07:43:24.470] ASTWorker running EnumerateTweaks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:24.470] --> reply:textDocument/codeAction(8) 176 ms
V[07:43:24.470] >>> {"id":8,"jsonrpc":"2.0","result":[]}

V[07:43:24.470] ASTWorker running DocumentLinks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:24.470] --> reply:textDocument/documentLink(9) 176 ms
V[07:43:24.470] >>> {"id":9,"jsonrpc":"2.0","result":[{"range":{"end":{"character":24,"line":4},"start":{"character":9,"line":4}},"target":"file:///home/ajit/work/pico/pico-sdk/src/common/pico_stdlib/include/pico/stdlib.h"}]}

V[07:43:24.470] ASTWorker running Highlights on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:24.470] --> reply:textDocument/documentHighlight(10) 176 ms
V[07:43:24.470] >>> {"id":10,"jsonrpc":"2.0","result":[]}

V[07:43:24.474] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":8}}

I[07:43:24.474] <-- $/cancelRequest
V[07:43:24.475] <<< {"id":11,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[{"code":"pp_file_not_found","message":"'stdio.h' file not found","range":{"end":{"character":18,"line":2},"start":{"character":9,"line":2}},"relatedInformation":[],"severity":1,"source":"clang"}]},"range":{"end":{"character":10,"line":2},"start":{"character":10,"line":2}},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.475] <-- textDocument/codeAction(11)
V[07:43:24.475] <<< {"id":12,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.475] <-- textDocument/documentLink(12)
V[07:43:24.475] ASTWorker running EnumerateTweaks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:24.475] --> reply:textDocument/codeAction(11) 0 ms
V[07:43:24.475] >>> {"id":11,"jsonrpc":"2.0","result":[]}

V[07:43:24.475] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":10}}

I[07:43:24.475] <-- $/cancelRequest
V[07:43:24.475] ASTWorker running DocumentLinks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:24.475] --> reply:textDocument/documentLink(12) 0 ms
V[07:43:24.475] >>> {"id":12,"jsonrpc":"2.0","result":[{"range":{"end":{"character":24,"line":4},"start":{"character":9,"line":4}},"target":"file:///home/ajit/work/pico/pico-sdk/src/common/pico_stdlib/include/pico/stdlib.h"}]}

V[07:43:24.475] <<< {"id":13,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":10,"line":2},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:24.475] <-- textDocument/documentHighlight(13)
V[07:43:24.475] ASTWorker running Highlights on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:24.475] --> reply:textDocument/documentHighlight(13) 0 ms
V[07:43:24.475] >>> {"id":13,"jsonrpc":"2.0","result":[]}

V[07:43:59.209] <<< {"id":14,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[{"code":"pp_file_not_found","message":"'stdio.h' file not found","range":{"end":{"character":18,"line":2},"start":{"character":9,"line":2}},"relatedInformation":[],"severity":1,"source":"clang"}]},"range":{"end":{"character":10,"line":2},"start":{"character":10,"line":2}},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:59.209] <-- textDocument/codeAction(14)
V[07:43:59.209] <<< {"id":15,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:59.209] <-- textDocument/documentLink(15)
V[07:43:59.210] <<< {"id":16,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":10,"line":2},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:43:59.210] <-- textDocument/documentHighlight(16)
V[07:43:59.210] ASTWorker running EnumerateTweaks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:59.210] --> reply:textDocument/codeAction(14) 0 ms
V[07:43:59.210] >>> {"id":14,"jsonrpc":"2.0","result":[]}

V[07:43:59.210] ASTWorker running DocumentLinks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:59.210] --> reply:textDocument/documentLink(15) 0 ms
V[07:43:59.210] >>> {"id":15,"jsonrpc":"2.0","result":[{"range":{"end":{"character":24,"line":4},"start":{"character":9,"line":4}},"target":"file:///home/ajit/work/pico/pico-sdk/src/common/pico_stdlib/include/pico/stdlib.h"}]}

V[07:43:59.210] ASTWorker running Highlights on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:43:59.210] --> reply:textDocument/documentHighlight(16) 0 ms
V[07:43:59.210] >>> {"id":16,"jsonrpc":"2.0","result":[]}

V[07:44:01.243] <<< {"id":17,"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":10,"line":2},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:44:01.243] <-- textDocument/hover(17)
V[07:44:01.243] ASTWorker running Hover on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
V[07:44:01.243] <<< {"id":18,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[{"code":"pp_file_not_found","message":"'stdio.h' file not found","range":{"end":{"character":18,"line":2},"start":{"character":9,"line":2}},"relatedInformation":[],"severity":1,"source":"clang"}]},"range":{"end":{"character":10,"line":2},"start":{"character":10,"line":2}},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:44:01.243] <-- textDocument/codeAction(18)
I[07:44:01.243] --> reply:textDocument/hover(17) 0 ms
V[07:44:01.243] >>> {"id":17,"jsonrpc":"2.0","result":null}

V[07:44:01.243] <<< {"id":19,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:44:01.243] <-- textDocument/documentLink(19)
V[07:44:01.243] ASTWorker running EnumerateTweaks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:44:01.243] --> reply:textDocument/codeAction(18) 0 ms
V[07:44:01.243] >>> {"id":18,"jsonrpc":"2.0","result":[]}

V[07:44:01.243] ASTWorker running DocumentLinks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:44:01.243] --> reply:textDocument/documentLink(19) 0 ms
V[07:44:01.243] >>> {"id":19,"jsonrpc":"2.0","result":[{"range":{"end":{"character":24,"line":4},"start":{"character":9,"line":4}},"target":"file:///home/ajit/work/pico/pico-sdk/src/common/pico_stdlib/include/pico/stdlib.h"}]}

V[07:44:01.243] <<< {"id":20,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":10,"line":2},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:44:01.243] <-- textDocument/documentHighlight(20)
V[07:44:01.243] ASTWorker running Highlights on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:44:01.243] --> reply:textDocument/documentHighlight(20) 0 ms
V[07:44:01.243] >>> {"id":20,"jsonrpc":"2.0","result":[]}

V[07:44:02.843] <<< {"id":21,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[{"code":"pp_file_not_found","message":"'stdio.h' file not found","range":{"end":{"character":18,"line":2},"start":{"character":9,"line":2}},"relatedInformation":[],"severity":1,"source":"clang"}]},"range":{"end":{"character":10,"line":2},"start":{"character":10,"line":2}},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:44:02.843] <-- textDocument/codeAction(21)
V[07:44:02.843] <<< {"id":22,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:44:02.843] <-- textDocument/documentLink(22)
V[07:44:02.843] ASTWorker running EnumerateTweaks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:44:02.843] --> reply:textDocument/codeAction(21) 0 ms
V[07:44:02.843] <<< {"id":23,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":10,"line":2},"textDocument":{"uri":"file:///home/ajit/work/pico/my/myblink3/src/myblink.c"}}}

I[07:44:02.843] <-- textDocument/documentHighlight(23)
V[07:44:02.843] >>> {"id":21,"jsonrpc":"2.0","result":[]}

V[07:44:02.843] ASTWorker running DocumentLinks on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:44:02.843] --> reply:textDocument/documentLink(22) 0 ms
V[07:44:02.843] >>> {"id":22,"jsonrpc":"2.0","result":[{"range":{"end":{"character":24,"line":4},"start":{"character":9,"line":4}},"target":"file:///home/ajit/work/pico/pico-sdk/src/common/pico_stdlib/include/pico/stdlib.h"}]}

V[07:44:02.843] ASTWorker running Highlights on version 0 of /home/ajit/work/pico/my/myblink3/src/myblink.c
I[07:44:02.843] --> reply:textDocument/documentHighlight(23) 0 ms
V[07:44:02.843] >>> {"id":23,"jsonrpc":"2.0","result":[]}

```

**Comment by HighCommander4** [comment]
The argument to query-driver needs to be the path to the gcc compiler executable. You can see from this line of the log, what value clangd is looking for:

> V[07:43:24.231] System include extraction: not allowed driver /usr/bin/arm-none-eabi-gcc

**Comment by ntn888** [comment]
okay thanks, i changed it:
```
(setq lsp-clients-clangd-args '("/usr/bin/arm-none-eabi-gcc" "--header-insertion-decorators=0" "--log=verbose"))

```
now server clangd exited with status exit:

```
Process clangd stderr finished
clangd: Unknown command line argument '/usr/bin/arm-none-eabi-gcc'.  Try: '/home/ajit/.emacs.d/.local/etclsp/clangd/clangd_13.0.0/bin/clangd --help'
```

**Comment by HighCommander4** [comment]
The executable name is the **value** of the `--query-driver` argument. You still need to write the argument name, as in:

```
--query-driver=/usr/bin/arm-none-eabi-gcc
```

**Comment by ntn888** [comment]
OH darn! thanks much!!

**Comment by ntn888** [comment]
just a follow-up...
do i have to comment this off when I work on native compilation? thanks again...

**Comment by HighCommander4** [comment]
> just a follow-up... do i have to comment this off when I work on native compilation? thanks again...

The argument to query-driver is basically an "allowlist" for compilers that clangd is allowed to execute for the purpose of querying their built-in include paths. The actual compiler to execute is taken from `compile_commands.json`, and checked against the allowlist.

So, when you're doing native compilation:
  * Presumably the commands in `compile_commands.json`, will contain the native compiler path, e.g. `/usr/bin/gcc`
  * Clangd will check this against the allowlist in `--query-driver`, i.e. `/usr/bin/arm-none-eabi-gcc`, and see that it's not allowed.
  * So clangd will not run the system include extractor. On most platforms, for native compilation, this works just fine.

A case where you may need to modify `--query-driver` is if you work with multiple cross-compilers. In this case, it's possible to make the allowlist a glob, e.g. `/usr/bin/*-gcc`.

**Comment by ntn888** [comment]
okay thanks for the clarification!
