### ISSUE TITLE
omp.h not found

### ISSUE THREAD

**Issue by wkjung** [clangd/clangd#971]
clangd complains it cannot find `omp.h`. After including the header as in https://github.com/clangd/clangd/issues/859#issuecomment-925680000, the error went away, but I'm not sure it is intended behavior (that I should add the header manually) because the compiler does its job well without `-I`.

x.cpp:
```cpp
#include <omp.h>
```

CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.0.0)
project(x VERSION 0.1.0)

find_package(OpenMP REQUIRED)
add_library(x x.cpp)
target_link_libraries(x PUBLIC OpenMP::OpenMP_CXX)
```

compile_commands.json:
```json
[
{ 
  "directory": "/home/wk/temp/x/build",
  "command": "/usr/bin/clang++-13   -g -fopenmp=libomp -o CMakeFiles/x.dir/x.cpp.o -c /home/wk/temp/x/x.cpp",
  "file": "/home/wk/temp/x/x.cpp"
}
]
```
**Logs**
```

Emits 'omp.h' file not found  (clang(pp_file_not_found)) error with the log below:

I[17:00:28.163] clangd version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
I[17:00:28.163] Features: linux+grpc
I[17:00:28.163] PID: 369665
I[17:00:28.163] Working directory: /home/wk/temp/x
I[17:00:28.163] argv[0]: /home/wk/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/bin/clangd
I[17:00:28.163] Starting LSP over stdin/stdout
I[17:00:28.171] <-- initialize(0)
I[17:00:28.171] --> reply:initialize(0) 0 ms
I[17:00:28.184] <-- initialized
I[17:00:28.184] <-- textDocument/didOpen
I[17:00:28.185] Loaded compilation database from /home/wk/temp/x/build/compile_commands.json
I[17:00:28.185] --> window/workDoneProgress/create(0)
I[17:00:28.185] ASTWorker building file /home/wk/temp/x/x.cpp version 1 with command 
[/home/wk/temp/x/build]
/usr/lib/llvm-13/bin/clang++-13 --driver-mode=g++ -g -fopenmp=libomp -o CMakeFiles/x.dir/x.cpp.o -c -resource-dir=/home/wk/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/lib/clang/13.0.0 -- /home/wk/temp/x/x.cpp
I[17:00:28.185] Enqueueing 1 commands for indexing
I[17:00:28.186] --> textDocument/clangd.fileStatus
I[17:00:28.187] <-- reply(0)
I[17:00:28.187] --> $/progress
I[17:00:28.187] --> $/progress
I[17:00:28.194] --> workspace/semanticTokens/refresh(1)
I[17:00:28.194] --> textDocument/clangd.fileStatus
I[17:00:28.195] <-- reply(1)
I[17:00:28.197] --> textDocument/publishDiagnostics
I[17:00:28.197] --> textDocument/clangd.fileStatus
I[17:00:28.240] <-- textDocument/codeAction(1)
I[17:00:28.240] <-- textDocument/documentLink(2)
I[17:00:28.240] <-- $/setTrace
I[17:00:28.240] unhandled notification $/setTrace
I[17:00:28.240] --> reply:textDocument/codeAction(1) 0 ms
I[17:00:28.240] --> reply:textDocument/documentLink(2) 0 ms
I[17:00:28.240] --> textDocument/clangd.fileStatus
I[17:00:28.267] <-- textDocument/semanticTokens/full(3)
I[17:00:28.267] --> reply:textDocument/semanticTokens/full(3) 0 ms
I[17:00:28.267] --> textDocument/clangd.fileStatus
I[17:00:28.287] <-- textDocument/codeAction(4)
I[17:00:28.287] --> reply:textDocument/codeAction(4) 0 ms
I[17:00:28.287] --> textDocument/clangd.fileStatus
I[17:00:28.294] <-- $/cancelRequest
I[17:00:28.294] <-- textDocument/codeAction(5)
I[17:00:28.294] --> reply:textDocument/codeAction(5) 0 ms
I[17:00:28.294] --> textDocument/clangd.fileStatus
I[17:00:28.904] <-- textDocument/documentSymbol(6)
I[17:00:28.904] --> reply:textDocument/documentSymbol(6) 0 ms
I[17:00:28.904] --> textDocument/clangd.fileStatus
I[17:00:29.503] <-- textDocument/codeAction(7)
I[17:00:29.503] --> reply:textDocument/codeAction(7) 0 ms
I[17:00:29.503] --> textDocument/clangd.fileStatus
I[17:00:29.566] <-- textDocument/documentLink(8)
I[17:00:29.566] --> reply:textDocument/documentLink(8) 0 ms
I[17:00:29.566] --> textDocument/clangd.fileStatus
I[17:00:29.900] <-- textDocument/documentLink(9)
I[17:00:29.901] --> reply:textDocument/documentLink(9) 0 ms
I[17:00:29.901] --> textDocument/clangd.fileStatus
I[17:00:30.352] <-- textDocument/documentLink(10)
I[17:00:30.352] --> reply:textDocument/documentLink(10) 0 ms
I[17:00:30.352] --> textDocument/clangd.fileStatus
I[17:00:30.433] <-- textDocument/documentLink(11)
I[17:00:30.433] --> reply:textDocument/documentLink(11) 0 ms
I[17:00:30.433] --> textDocument/clangd.fileStatus
```

**System information**

Output of `clangd --version`: 13.0.0

Editor/LSP plugin: vscode clangd

Operating system: ubuntu 20.04.3 LTS

cmake: 3.21.0

**Comment by sam-mccall** [comment]
Hmm, it looks like:
 - `<omp.h>` is supposed to be a builtin header shipped with the tool (clangd)
 - while clang's parser has openmp support in any case, the `<omp.h>` header is only built if `-DLLVM_ENABLE_PROJECTS` includes `openmp`.
 - we don't set that flag when building our github releases

We should fix the github releases.

How did you get your clangd binary? If from github (which includes installed from within the vscode plugin itself) then fixing github releases should be enough. Otherwise we'll also need to fix wherever the release was built.

BTW if you don't like your current workaround, copying `omp*.h` **from a same-version clang** seems reasonable. e.g. on my system `cp /usr/lib/clang/13.0.0/include/omp*.h ~/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/lib/clang/13.0.0/include/`

**Comment by wkjung** [comment]
@sam-mccall Got clangd binary from GitHub, as vscode plugin suggested.

The workaround seems good for me. Hope it gets fixed soon.

**Comment by sam-mccall** [comment]
This should be picked up in the next snapshot build in ~5 days.

**Comment by wkjung** [comment]
@sam-mccall Is the patch applied to the current release of clangd vscode extension? 
After clean-installing clangd vscode extension 0.1.15 I still cannot find `omp.h` in `..../llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/lib/clang/13.0.0/include/**`.

**Comment by HighCommander4** [comment]
@wkjung the fix is on the server side (clangd), not in vscode-clangd. You can download a weekly snapshot release of clangd [here](https://github.com/clangd/clangd/releases), or wait for version 14 to be released.

**Comment by realHarvey** [comment]
I had met the same trouble, but when I check my clang and clangd version, it's `clang-10` and `clangd-12`, I use `update-alternatives` to turn to `clangd-10`, it works.   (I use gcc-9 in Ubuntu-20.04

**Comment by r-dimajo** [comment]
I met the same issue using vscode plugin with latest `clangd22.1.0`. However, this workaround still work.

> Hmm, it looks like:
> 
> * `<omp.h>` is supposed to be a builtin header shipped with the tool (clangd)
> * while clang's parser has openmp support in any case, the `<omp.h>` header is only built if `-DLLVM_ENABLE_PROJECTS` includes `openmp`.
> * we don't set that flag when building our github releases
> 
> We should fix the github releases.
> 
> How did you get your clangd binary? If from github (which includes installed from within the vscode plugin itself) then fixing github releases should be enough. Otherwise we'll also need to fix wherever the release was built.
> 
> BTW if you don't like your current workaround, copying `omp*.h` **from a same-version clang** seems reasonable. e.g. on my system `cp /usr/lib/clang/13.0.0/include/omp*.h ~/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/lib/clang/13.0.0/include/`

**Comment by HighCommander4** [comment]
> I met the same issue using vscode plugin with latest `clangd22.1.0`.

That looks like a regression in the 22.x packages. Please follow https://github.com/clangd/clangd/issues/2634 for updates.
